name: wazo-webrtc-demo
namespace: official/wazo-webrtc-demo
version: 0.0.1
author: Wazo Team
display_name: WebRTC client demo
tags:
  - demo
  - community
homepage: https://github.com/wazo-platform/wazo-webrtc-demo
